### ISSUE TITLE
[Issue] Compressed Stone 3 Recipe

### ISSUE THREAD

**Issue by HalcyonSeas73** [nanite/Compressium#1]
### Mod version

1.2.3+mc1.16.5

### Forge mod loader version

36.2.8

### Repeatable?

- [X] Yes

### Steps to reproduce the issue

1. Create a 3x3 stack of Compressed Stone 3
2. This does not result in a recipe for Compressed Stone 4.

### Description of the issue you are having

The recipe for Compressed Stone 4 does not exist; having 3x3 of Compressed Stone 3 does not create Compressed Stone 4.

Additionally, according to JEI, Compressed Stone 4 does not have a prerequisite.

### Information

- [X] I have provided as much information as possible

**Comment by DinnerBeef** [comment]
I dont have a version named that. Where did you get this mod from or what pack are you playing?

**Comment by HalcyonSeas73** [comment]
> 
> 
> I dont have a version named that. Where did you get this mod from or what pack are you playing?

Ah, sorry, I meant 1.2.3. I was looking at MultiMC's "version" column, which shows 1.1 for some reason.

**Comment by DinnerBeef** [comment]
its works for me? did you download this form a pack if so what one?

**Comment by HalcyonSeas73** [comment]
Wow, okay, so I think I got Compressium mixed up with a similarly-named mod (Compressed). Please disregard both of the issues I created.
