### ISSUE TITLE
[Issue] Duplicate block entries make the game unable to load

### ISSUE THREAD

**Issue by Raidobw2** [nanite/Compressium#13]
### Mod version

Compressium-1.4.1-build.6+mc1.18.2.jar

### Forge mod loader version

40.1.76

### Repeatable?

- [X] Yes

### Link to log files

Latest log: https://paste.feed-the-beast.com/view/773cbc72
[latest.log](https://github.com/nanite/Compressium/files/9796419/latest.log)

Problematic config file: https://paste.feed-the-beast.com/view/4071b149
[compressiumblocks.txt](https://github.com/nanite/Compressium/files/9796581/compressiumblocks.txt)

Shipped config file: https://paste.feed-the-beast.com/view/23ae0d52
[compressiumblocks.txt](https://github.com/nanite/Compressium/files/9796595/compressiumblocks.txt)

### Steps to reproduce the issue

Put the problematic config file into your config for the mod and start the game. It will crash.

If you use the other config, it works.

### Description of the issue you are having

Some users playing FTB Plexiglass Mountain reported in the FTB Discord that they tried playing the pack and it crashed with the error in the log. The shipped config file for PGM's latest version (1.2.0) is linked above and contains the base content generated by the mod (it should be unmodified).

I don't know how the problematic config file got duplicate entries, but it did. Maybe if the mod loads a couple of time this can be reproduced? Or possibly a crash or anormal exiting of the game lead to this

The fix was to delete the config file and let it regenerate, then the game load continued as normal.

I'd like to suggest that the mod would skip duplicate JSON nodes if any, or maybe there is something else to check to prevent it from creating duplicate entries, that would also be nice

Thanks in advance for looking into this when you have time!

### Information

- [X] I have provided as much information as possible

**Comment by DinnerBeef** [comment]
Fixed! https://www.curseforge.com/minecraft/mc-mods/compressium/files/4034865

**Comment by Raidobw2** [comment]
Yay 🎉😄 Thanks to you and Mikey!
