### ISSUE TITLE
[Issue] compressium "Duplicate registration iron_1" error

### ISSUE THREAD

**Issue by ScarFia** [nanite/Compressium#16]
### Minecraft Version

1.19.2

### Modloader

forge-43.2.7

### Mod version

Compressium-2.1.1-build.8+mc1.19

### Repeatable?

- [ ] Yes

### Link to log files

[crash-2023-05-09_15.09.51-fml.txt](https://github.com/nanite/Compressium/files/11431467/crash-2023-05-09_15.09.51-fml.txt)

### Description of the issue you are having

I am trying to start modpack server for "techopolis 2" from benbenlaw and i am taking this error.

I think this cause the issue "java.lang.IllegalArgumentException: Duplicate registration iron_1" 

### Information

- [X] I have provided as much information as possible

**Comment by b0bst3r** [comment]
@enessmsr I know this was a long time ago but we've had a person with this exact issue on discord that I've been trying to fix.  Do you remember how you fixed this?

**Comment by ScarFia** [comment]
![Screenshot_4](https://github.com/nanite/Compressium/assets/53229064/cfed459e-158b-4db4-9fbb-caf55fae2c46)
As far as I remember I turned on "Valid language for non-Unicode programs is UTF-8" in the language settings

**Comment by b0bst3r** [comment]
We fixed his issue, he had system language set as Turkish and when he switched it to english it seemed to fix this issue.  Was your initial language always English(US)?

**Comment by ScarFia** [comment]
No, mine was Turkish too. It seems Turkish bugging the server
