### ISSUE TITLE
[Issue] [1.20] Compressed block only returns 1 when uncompressed rather than 9

### ISSUE THREAD

**Issue by Zedrimar** [nanite/Compressium#17]
### Minecraft Version

1.20

### Modloader

Forge 46.0.14

### Mod version

 Compressium-3.0.1-build.11+mc1.20.jar

### Repeatable?

- [x] Yes

### Link to log files

https://pastebin.com/vvh1CQJZ

### Steps to reproduce the issue

1. Create or spawn compressed block
2. uncompress block in crafting grid
3. Profit?

### Description of the issue you are having

Trying to uncompress a block only returns 1 of that block/block of tier below it rather than 9. Same issue regardless of forge version. I didn't look thuroughly but I could not find anything amiss specific to this mod in the logs. Submitting logs anyway, maybe there's something I didn't see. Issue applies to all compressed blocks.

### Information

- [X] I have provided as much information as possible

**Comment by DinnerBeef** [comment]
Fixed should have an updated build on curseforge soon

**Comment by Zedrimar** [comment]
Thank you :)
