### ISSUE TITLE
[Feature Request] Additional Blocks

### ISSUE THREAD

**Issue by HalcyonSeas73** [nanite/Compressium#3]
### Feature Description

Compression Blocks for: 

- Basalt
- Blackstone
- Grass Block
- Prismarine
- Dark Prismarine
- Purpur Blocks
- Podzol
- Magma Block
- Soul Soil
- Glowstone
- Melon/Pumpkin
- Bricks/Nether Bricks/Red Nether Bricks
- Sugar Cane
- Bamboo
- Charcoal

Perhaps the vanilla Logs as well:

- Jungle
- Oak
- Birch
- Dark Oak
- Acacia
- Spruce
- Crimson Stem
- Warped Stem

**Comment by BigAl607** [comment]
Would like to see the new blocks added as well - Deepslate, Cobbled Deepslate, Tuff, etc.

**Comment by SimplyAG** [comment]
2nd for all the blocks said above

**Comment by HalcyonSeas73** [comment]
There hasn't been any comment from the author yet; are there plans to update the mod to include the common 1.18 blocks like Tuff and Deepslate?

**Comment by DinnerBeef** [comment]
One day I will add some more block. Been busy doing other things

**Comment by SimplyAG** [comment]
> One day I will add some more block. Been busy doing other things

No worries thanks for the reply!

**Comment by DinnerBeef** [comment]
newest version coming out soon. Will allow you to add your own blocks
