### ISSUE TITLE
SkyFactory One - compressed cobblestone textures appear to be same as regular cobblestone, impossible to disinguish vishally

### ISSUE THREAD

**Issue by grannymc** [nanite/Compressium#4]
### Mod version

1.16.5-1.2.3

### Forge mod loader version

36.2.230

### Repeatable?

- [X] Yes

### Link to log files

n/a

### Steps to reproduce the issue

Place blocks in hot bar or on ground and look at them

### Description of the issue you are having

All of the compressed cobblestone textures look like the regular MC cobble texture and are visually indistinguishable. 

### Information

- [X] I have provided as much information as possible

**Comment by DinnerBeef** [comment]
do you have a screenshot please?

**Comment by grannymc** [comment]
I think I forgot to save an edit to the original report. Sorry. It only has
this problem in inventories and JEI, not when placed. Here's a PNG: Let me
know if you need more info.

I did add a couple mods: Pam's Food Core, AppleSkin, and Fast Leaf Decay.
Otherwise it's the current version of SFOne.

hotbar/JEI, stack is regular cobble, hotbar are 1x, 2x, etc. in order
[image: 2022-02-14_16.33.38.png]

**Comment by DinnerBeef** [comment]
you seem to have not attached the image correctly

**Comment by grannymc** [comment]
![2022-02-14_16 33 38](https://user-images.githubusercontent.com/39201153/153951825-3cd083a0-5002-4229-b82b-e696ebd56d7e.png)

**Comment by DinnerBeef** [comment]
are you using a texture pack?

**Comment by grannymc** [comment]
No. Strictly vanilla. Would you like the world file?

**Comment by grannymc** [comment]
I haven't tried reloading the pack. Let me do that and get back to you.

**Comment by grannymc** [comment]
welp, now it's not doing it after restarting the pack. I will let you know if it happens again and see if I can figure out what I was doing before that. Thanks for your time.

**Comment by DinnerBeef** [comment]
All right
