### ISSUE TITLE
[Feature Request]

### ISSUE THREAD

**Issue by karikusa** [nanite/Compressium#6]
### Feature Description

[Deepslate]
[Cobbled Deepslate]
I think these two types of compression blocks would be perfect!

**Comment by DinnerBeef** [comment]
you can add them you to the game you self if you want just need to add them to the compressiumblocks.json in the config folder

**Comment by karikusa** [comment]
I tried several times, but I couldn't add the compression block successfully ...
Because I can't think logically to understand the program well
I respect the people who can make it ...

**Comment by DinnerBeef** [comment]
See issue #7

**Comment by karikusa** [comment]
I added it with reference to # 7.
Purple and black textured objects are made,
Items without recipes have been added
Subsequent comments didn't make sense.
What is an IDE?
